name: DevSecOps Pipeline for Juice Shop

on:
  push:
    branches:
      - main

jobs:
  pull_image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull bkimminich/juice-shop:latest

  test:
    runs-on: ubuntu-latest
    needs: pull_image
    steps:
      - name: Run Tests
        run: |
          docker run --rm -d --name juice_shop_test bkimminich/juice-shop:latest
          docker exec juice_shop_test npm run test
          docker stop juice_shop_test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Juice Shop
        run: docker run -d --name juice_shop -p 3000:3000 bkimminich/juice-shop:latest
