name: "CI/CD Pipeline"

on:
  push:
    branches-ignore:
      - l10n_develop
      - gh-pages
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "monitoring/grafana-dashboard.json"
      - "screenshots/**"
    tags-ignore:
      - "*"
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "data/static/i18n/*.json"
      - "frontend/src/assets/i18n/*.json"

env:
  NODE_DEFAULT_VERSION: 20
  ANGULAR_CLI_VERSION: 17

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4
      - name: "Use Node.js ${{ env.NODE_DEFAULT_VERSION }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_DEFAULT_VERSION }}
      - name: "Install Angular CLI"
        run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION
      - name: "Install dependencies (minimal)"
        run: |
          npm install --ignore-scripts
          cd frontend
          npm install --ignore-scripts --legacy-peer-deps
      - name: "Run linting"
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: npm install
      - name: "Run unit tests"
        run: npm test
      - name: "Collect coverage data"
        run: |
          cp build/reports/coverage/frontend-tests/lcov.info frontend-lcov.info
          cp build/reports/coverage/server-tests/lcov.info server-lcov.info
      - name: "Upload coverage artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            frontend-lcov.info
            server-lcov.info

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4
      - name: "Use Node.js ${{ env.NODE_DEFAULT_VERSION }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_DEFAULT_VERSION }}
      - name: "Install dependencies"
        run: npm install
      - name: "Run integration tests"
        run: npm run test:integration
